const api = {
    /**获取获取学习活动列表 */
    getActivityList: '/wil/learningActivity/list',
    /**获取课程学习资源 */
    getStudyResources: '/wil/learningActivity/learningResources',
    /**学生获取学习成果 */
    getStudyGain: '/wil/learningActivity/outcomes',
    /**老师获取学习成果 */
    getTeacherStudyGain: '/wil/learningActivity/outcomesByActivity',
    /**获取学生课后作业  */
    getStudyHomework: '/wil/homework/getByStudent',
    /**编辑保存学习成果（待提交） */
    getStudyGainFile: '/wil/learningActivity/outcome/edit',
    /**提交学习成果 */
    submitStudyGain: '',
    /**提交课后作业的编辑内容 */
    submitHomeworkEdit: '/wil/homework/edit',
    /**提交全部课后作业 */
    submitAllHomework: '/wil/homework/submit',
    /**获取提交状态 */
    getSubmissionStatus: '/wil/learningActivity/submissionStatus',
    /**班级学习活动各状态统计 */
    getClassStatusStatistics: '/wil/learningActivity/classStatusStatistics',
    /**获取提交者课后作业详情 */
    getSubmitterHomework: '/wil/homework/getStudentHomeworkByHk',
    /**获取提交者学习成果详情 */
    getSubmitterOutcome: '/wil/learningActivity/submitterOutcome',
    /**根据模版创建web文件 */
    createWebFileByTemplate: '/wil/web_file/wps/create_web_file_code',
    /**获取模版详情 */
    getMindJsonByTemplate: '/wil/resource_library/detail',
    /**新建资源 */
    bindWpsAndResource: '/wil/resource_library/create',
    /**提交学习成果的编辑内容 */
    submitStudyGainEdit: '/wil/learningActivity/outcome/edit',
    /**提交活动内容 */
    submitActivity: '/wil/learningActivity/submit',
    /**获取课堂测验题目 */
    getQuestionList: '/wil/learningActivity/question',
    /**提交课堂测验 */
    submitQuestion: '/wil/learningActivity/answer',
    /**获取课堂测验题目(老师) */
    getQuestionAnswer: '/wil/class_question/question',
    /**获取课程考核构成 */
    getCourseEvaluations: '/wil/evaluation/courseEvaluations',
}
export default api
