export interface Objtype {
    code: string
    merchantOrgCode: string
    mchtOrgType: number
    draft: number
    name: string
    shortName: string
    bizType: number
    status: number
    failReason: string
    identityType: number
    identityNo: string
    orgCode: string
    orgCodeEffect: null
    orgCodeExpiration: null
    taxCode: string
    taxCodeEffect: null
    taxCodeExpiration: null
    productList: string
    province: string
    city: string
    zone: string
    addressDetail: string
    mchtPhone: string
    mccCode: string
    crossBorder: number
    nativeType: string
    sameLegal: number
    nativeName: string
    nativeIdentityType: number
    nativeIdentityNo: string
    nativeIdentityEffect: null
    nativeIdentityExpiration: null
    nativePhone: string
    account: string
    accountName: string
    accountType: number
    openingBankName: string
    openingBankProvince: string
    openingBankCity: string
    openingBankAddress: string
    feeAccount: string
    feeAccountName: string
    refundAccount: string
    refundAccountName: string
    expireTime: number
    signUrl: string
    bizLicensePic: string
    legalIdentityPicFront: string
    legalIdentityPicBack: string
    beneficiaryIdentityPicBack: string,
    beneficiaryIdentityPicFront: string,
    bizPlacePic1: string
    bizPlacePic2: string
    bizPlacePic3: string
    bizPlacePic4: string
    bizPlacePic5: string
}
