export const EXAM_REPORT_PAPER_COLUMNS = [
    {
        title: '答对人数/实考人数',
        dataIndex: 'right_count',
        key: 'right_count',
    },
    {
        title: '正确率',
        dataIndex: 'right_rate',
        key: 'right_rate',
    },
    {
        title: '试题难度系数',
        dataIndex: 'difficulty_coefficient',
        key: 'difficulty_coefficient',
    },
    {
        title: '试题区分度',
        dataIndex: 'difficulty_degree',
        key: 'difficulty_degree',
    },
    {
        title: '平均答题时长',
        dataIndex: 'average_answer_time',
        key: 'average_answer_time',
    },
]

export const EXAM_REPORT_QUESTION_COLUMNS = [
    {
        title: '罗云奇',
        children: [
            {
                title: '得分',
                dataIndex: 'student1_score',
                key: 'student1_score',
                align: 'center',
            },
            {
                title: '答题时长',
                dataIndex: 'student1_time',
                key: 'student1_time',
                align: 'center',
            },
        ],
    },
    {
        title: '王先恒',
        children: [
            {
                title: '得分',
                dataIndex: 'student2_score',
                key: 'student2_score',
                align: 'center',
            },
            {
                title: '答题时长',
                dataIndex: 'student2_time',
                key: 'student2_time',
                align: 'center',
            },
        ],
    },
    {
        title: '章广飞',
        children: [
            {
                title: '得分',
                dataIndex: 'student3_score',
                key: 'student3_score',
                align: 'center',
            },
            {
                title: '答题时长',
                dataIndex: 'student3_time',
                key: 'student3_time',
                align: 'center',
            },
        ],
    },
]

export const EXAM_REPORT_PAPER_MOCK = [
    {
        question_index: '1',
        right_count: '3/3',
        right_rate: '100%',
        difficulty_coefficient: '1',
        difficulty_degree: '0',
        average_answer_time: '01:15',
    },
    {
        question_index: '2',
        right_count: '2/3',
        right_rate: '66%',
        difficulty_coefficient: '0.67',
        difficulty_degree: '1',
        average_answer_time: '01:24',
    },
    {
        question_index: '3',
        right_count: '1/3',
        right_rate: '33%',
        difficulty_coefficient: '0.33',
        difficulty_degree: '1',
        average_answer_time: '03:07',
    },
    {
        question_index: '4',
        right_count: '1/3',
        right_rate: '33%',
        difficulty_coefficient: '0.33',
        difficulty_degree: '1',
        average_answer_time: '02:03',
    },
    {
        question_index: '5',
        right_count: '3/3',
        right_rate: '100%',
        difficulty_coefficient: '1',
        difficulty_degree: '0',
        average_answer_time: '02:12',
    },
    {
        question_index: '6',
        right_count: '1/3',
        right_rate: '33%',
        difficulty_coefficient: '0.33',
        difficulty_degree: '1',
        average_answer_time: '03:19',
    },
    {
        question_index: '7',
        right_count: '2/3',
        right_rate: '66%',
        difficulty_coefficient: '0.67',
        difficulty_degree: '0',
        average_answer_time: '00:57',
    },
    {
        question_index: '8',
        right_count: '2/3',
        right_rate: '66%',
        difficulty_coefficient: '0.67',
        difficulty_degree: '1',
        average_answer_time: '00:42',
    },
    {
        question_index: '9',
        right_count: '--',
        right_rate: '--',
        difficulty_coefficient: '0.5',
        difficulty_degree: '0.58',
        average_answer_time: '04:48',
    },
    {
        question_index: '10',
        right_count: '--',
        right_rate: '--',
        difficulty_coefficient: '0.83',
        difficulty_degree: '0.68',
        average_answer_time: '05:36',
    },
]

export const EXAM_REPORT_QUESTION_MOCK = [
    {
        question_index: '1',
        student1_score: '10',
        student1_time: '01:40',
        student2_score: '10',
        student2_time: '01:20',
        student3_score: '10',
        student3_time: '00:45',
    },
    {
        question_index: '2',
        student1_score: '10',
        student1_time: '01:54',
        student2_score: '0',
        student2_time: '01:42',
        student3_score: '10',
        student3_time: '00:36',
    },
    {
        question_index: '3',
        student1_score: '0',
        student1_time: '02:58',
        student2_score: '0',
        student2_time: '03:31',
        student3_score: '10',
        student3_time: '02:45',
    },
    {
        question_index: '4',
        student1_score: '10',
        student1_time: '01:55',
        student2_score: '10',
        student2_time: '02:39',
        student3_score: '10',
        student3_time: '01:35',
    },
    {
        question_index: '5',
        student1_score: '10',
        student1_time: '02:26',
        student2_score: '10',
        student2_time: '02:30',
        student3_score: '10',
        student3_time: '01:40',
    },
    {
        question_index: '6',
        student1_score: '0',
        student1_time: '03:52',
        student2_score: '0',
        student2_time: '03:12',
        student3_score: '10',
        student3_time: '02:38',
    },
    {
        question_index: '7',
        student1_score: '10',
        student1_time: '01:08',
        student2_score: '10',
        student2_time: '01:11',
        student3_score: '10',
        student3_time: '00:32',
    },
    {
        question_index: '8',
        student1_score: '0',
        student1_time: '00:52',
        student2_score: '0',
        student2_time: '00:46',
        student3_score: '10',
        student3_time: '00:28',
    },
    {
        question_index: '9',
        student1_score: '5',
        student1_time: '05:17',
        student2_score: '5',
        student2_time: '04:47',
        student3_score: '5',
        student3_time: '04:20',
    },
    {
        question_index: '10',
        student1_score: '10',
        student1_time: '06:18',
        student2_score: '10',
        student2_time: '05:46',
        student3_score: '5',
        student3_time: '05:02',
    },
]

export const EXAM_REPORT_QUESTION_DETAIL_MOCK = {
    1: {
        question_stem: '条形码符号由（）组成，以不同宽度代表不同的基本数字和字符。',
        question_type: '单选题',
        question_options: ['点和线', '条和空', '二维码', '彩色码'],
        right_answers: 'B',
        analysis: '-',
    },
    2: {
        question_stem: '从信息传递层次看，信息传递方式有（）。',
        question_type: '单选题',
        question_options: [
            '单向信息传递和双向信息传递',
            '直接传递和间接传递',
            '时间传递和空间传递',
            '人工传递和非人工传递',
        ],
        right_answers: 'B',
        analysis: '-',
    },
    3: {
        question_stem: '网络客户服务最大的优势在于（）。',
        question_type: '单选题',
        question_options: [
            '价格非常低廉，效果更佳',
            '能够轻松打败竞争对手',
            '能够与客户建立起持久的一对一服务关系',
            '信息传递的及时性',
        ],
        right_answers: 'C',
        analysis: '-',
    },
    4: {
        question_stem: '关于客户服务，说法错误的是（）。',
        question_type: '单选题',
        question_options: [
            '简而言之就是企业为客户提供各种各样的服务',
            '是一种活动、绩效水平和管理理念',
            '以客户为依托，以产品或服务为对象',
            '使企业和客户的价值都得到提升的活动过程',
        ],
        right_answers: 'C',
        analysis: '-',
    },
    5: {
        question_stem: '（）是企业客户服务的出发点。',
        question_type: '单选题',
        question_options: ['提供高效服务', '提供完美服务', '客户关系管理', '满足客户需求'],
        right_answers: 'D',
        analysis: '-',
    },
    6: {
        question_stem: '我国跨境电子商务，主要有（    ）等具体模式',
        question_type: '多选题',
        question_options: ['直销模式', '海外代购平台模式', '传销模式', '直发/直运平台模式'],
        right_answers: 'B D',
        analysis: '-',
    },
    7: {
        question_stem: '网站的主要内容围绕核心关键词展开',
        question_type: '判断题',
        question_options: ['正确', '错误'],
        right_answers: '正确',
        analysis: '-',
    },
    8: {
        question_stem: '长尾关键词一般由两个词语或三个词语组成，甚至是一句短语。',
        question_type: '判断题',
        question_options: ['正确', '错误'],
        right_answers: '正确',
        analysis: '-',
    },
    9: {
        question_stem: '当遇到一个关于交易处理延迟的问题时，你如何利用设计缺陷知识库进行问题分析？',
        question_type: '简答题',
        question_options: undefined,
        right_answers:
            '(1)查找知识库中关于交易处理延迟的常见原因，包括数据库性能瓶颈和网络延迟问题。(2)分析问题发生的时间点和频率，与知识库中的缺陷模式进行对比，以缩小可能的原因范围。',
        analysis: '-',
    },
    10: {
        question_stem: '描述你在编写技术交底提纲时会包含哪些关键技术信息？请至少列举三项。',
        question_type: '简答题',
        question_options: undefined,
        right_answers:
            '(1)详细描述系统架构，包括硬件和软件的配置要求。(2)列出关键业务流程和数据流，以及ERP系统如何支持这些流程。(3)包括安全和合规性要求，确保系统满足行业标准和法规。',
        analysis: '-',
    },
}

export const EXAM_REPORT_QUESTION_OPTIONS_LABEL = ['A', 'B', 'C', 'D']
