export const mockObj = {
    key: '169384318NP9W64Q',
    title: '练习',
    route: '',
    children: [
        {
            key: '169384318O828M4G',
            title: '练习列表',
            route: '/practice/list',
            children: [],
            operate: false,
            alias: 'PRACTICE_LIST',
            id: '169384318O828M4G',
            type: 'PRACTICE_LIST',
            icon: '',
            parentCode: '169384318NP9W64G',
            layoutHeader: 0,
            layoutMenu: 0,
        },
        {
            key: '169384318OLFV30G',
            title: '练习详情',
            route: '/practice/details',
            children: [],
            operate: false,
            alias: 'PRACTICE_DETAILS',
            id: '169384318OLFV30G',
            type: 'PRACTICE_DETAILS',
            icon: '',
            parentCode: '169384318NP9W64G',
            layoutHeader: 0,
            layoutMenu: 0,
        },
        {
            key: '169384318P0BT728',
            title: '我的练习',
            route: '/exam-center/practice-list',
            children: [],
            operate: false,
            alias: 'MY_PRACTICE',
            id: '169384318P0BT728',
            type: 'MY_PRACTICE',
            icon: '',
            parentCode: '169384318NP9W64G',
            layoutHeader: 0,
            layoutMenu: 0,
        },
    ],
    operate: false,
    alias: 'PRACTICE',
    id: '169384318NP9W64G',
    type: 'group',
    icon: '',
    parentCode: '-1',
    layoutHeader: 0,
    layoutMenu: 0,
}
