export const templateTableList = [
    { questionType: 10 },
    { questionType: 20 },
    { questionType: 30 },
    { questionType: 40 },
    { questionType: 50 },
    { questionType: 60 },
    { questionType: 70 },
    { questionType: 80 },
    { questionType: 90 },
]
export const compositionClearValues = {
    authenticateCode: undefined,
    fromFileCode: '',
    fromFileTitle: '',
    scoreType: 'questiontype',
    unificationScore: undefined,
    qualifiedProp: undefined,
    questionStructure: 'questiontype',
    questionConfigList: [],
    questionTableData: [],
    templateTableList: templateTableList,
    questionTotal: 0,
    questionTypeLeast: 0,
    suggestedTime: 0,
    precautions: '',
    canEditState: 1,
    randomQuestionState: 0,
    randomQuestionNum: 0,
    chaosOrderState: false,
    chaosOptionsState: false,
    numContinuousState: false,
    receiptStatus: false,
    receiptStartTime: 0,
    receiptEndTime: 0,
    quoteNumStatus: false,
    questionCitedLimit: undefined,
}
export const clearValues = {
    composition: 'authenticate',
    ...compositionClearValues,
}
